# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SleepAP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SleepAP
   pod 'Parse'
  target 'SleepAPTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end

  target 'SleepAPUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Parse'
  end



end
